# Generated by Django 5.2.1 on 2025-08-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_applicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
