# Generated by Django 5.2.1 on 2025-08-05 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userrole_can_view_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUptimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('startup', 'System Startup'), ('shutdown', 'System Shutdown')], max_length=10)),
                ('boot_time', models.DateTimeField(blank=True, help_text='System boot time from psutil', null=True)),
            ],
            options={
                'verbose_name_plural': 'System Uptime Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
