# Generated by Django 5.2.5 on 2025-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_system_uptime_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(choices=[('auth_login', 'Login'), ('auth_logout', 'Logout'), ('auth_failed', 'Failed Login'), ('auth_password_change', 'Password Change'), ('auth_password_reset', 'Password Reset'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_role_change', 'Role Changed'), ('user_permission_change', 'Permission Changed'), ('user_profile_update', 'Profile Updated'), ('security_event', 'Security Event'), ('security_scan', 'Security Scan'), ('security_alert', 'Security Alert'), ('system_startup', 'System Startup'), ('system_shutdown', 'System Shutdown'), ('system_update', 'System Update'), ('system_config_change', 'Configuration Change'), ('network_scan', 'Network Scan'), ('network_device_added', 'Device Added'), ('network_device_updated', 'Device Updated'), ('network_device_removed', 'Device Removed'), ('network_device_status_change', 'Device Status Change'), ('api_access', 'API Access'), ('admin_action', 'Admin Action'), ('data_create', 'Data Created'), ('data_update', 'Data Updated'), ('data_delete', 'Data Deleted')], max_length=50),
        ),
    ]
