# Generated by Django 5.2.1 on 2025-08-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_applicationlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name for the certificate', max_length=255)),
                ('encrypted_certificate', models.TextField(help_text='AES-256 encrypted certificate data')),
                ('encrypted_private_key', models.TextField(help_text='AES-256 encrypted private key data')),
                ('salt', models.CharField(help_text='Salt for key derivation', max_length=64)),
                ('iv', models.CharField(help_text='Initialization vector for encryption', max_length=32)),
                ('subject', models.CharField(blank=True, help_text='Certificate subject', max_length=500)),
                ('issuer', models.CharField(blank=True, help_text='Certificate issuer', max_length=500)),
                ('serial_number', models.CharField(blank=True, help_text='Certificate serial number', max_length=100)),
                ('not_valid_before', models.DateTimeField(blank=True, null=True)),
                ('not_valid_after', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, help_text='SHA-256 fingerprint', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ssl_certificates',
            },
        ),
        migrations.CreateModel(
            name='SSLCertificateUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Certificate Created'), ('accessed', 'Certificate Accessed'), ('updated', 'Certificate Updated'), ('deleted', 'Certificate Deleted'), ('downloaded', 'Certificate Downloaded')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api.usersslcertificate')),
            ],
            options={
                'db_table': 'ssl_certificate_usage_logs',
            },
        ),
        migrations.AddIndex(
            model_name='usersslcertificate',
            index=models.Index(fields=['user', 'created_at'], name='user_ssl_ce_user_id_65df83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersslcertificate',
            index=models.Index(fields=['fingerprint'], name='user_ssl_ce_fingerp_8a5931_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersslcertificate',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='sslcertificateusagelog',
            index=models.Index(fields=['certificate', 'timestamp'], name='ssl_certifi_certifi_b706c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificateusagelog',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='ssl_certifi_user_id_788bcb_idx'),
        ),
    ]
