# Generated by Django 5.2.1 on 2025-08-07 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usersslcertificate_sslcertificateusagelog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersslcertificate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersslcertificate',
            name='user',
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this SSH key', max_length=255)),
                ('key_type', models.CharField(choices=[('rsa', 'RSA'), ('ed25519', 'Ed25519'), ('ecdsa', 'ECDSA')], default='rsa', max_length=50)),
                ('fingerprint', models.CharField(help_text='SSH key fingerprint', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ssh_keys',
            },
        ),
        migrations.CreateModel(
            name='SSHSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SSH target host', max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(help_text='SSH username', max_length=100)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='connecting', max_length=20)),
                ('ssh_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sshkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssh_sessions',
            },
        ),
        migrations.DeleteModel(
            name='SSLCertificateUsageLog',
        ),
        migrations.DeleteModel(
            name='UserSSLCertificate',
        ),
        migrations.AddIndex(
            model_name='sshkey',
            index=models.Index(fields=['user', 'created_at'], name='user_ssh_ke_user_id_0afde8_idx'),
        ),
        migrations.AddIndex(
            model_name='sshkey',
            index=models.Index(fields=['fingerprint'], name='user_ssh_ke_fingerp_580ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='sshsession',
            index=models.Index(fields=['user', 'started_at'], name='ssh_session_user_id_6508b1_idx'),
        ),
        migrations.AddIndex(
            model_name='sshsession',
            index=models.Index(fields=['session_id'], name='ssh_session_session_0b1614_idx'),
        ),
        migrations.AddIndex(
            model_name='sshsession',
            index=models.Index(fields=['status'], name='ssh_session_status_8cc6fd_idx'),
        ),
    ]
