# Generated by Django 5.2.5 on 2025-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fix_can_view_logs_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30, help_text='Session timeout in minutes. 0 means never timeout.'),
        ),
    ]
