# Generated by Django 5.2.5 on 2025-08-14 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_session_timeout_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAPICache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='GitHub API URL', max_length=500, unique=True)),
                ('etag', models.CharField(blank=True, help_text='ETag from GitHub response', max_length=100, null=True)),
                ('last_modified', models.CharField(blank=True, help_text='Last-Modified header from GitHub', max_length=100, null=True)),
                ('response_data', models.JSONField(help_text='Cached response data from GitHub API')),
                ('status_code', models.IntegerField(default=200, help_text='HTTP status code from GitHub')),
                ('cached_at', models.DateTimeField(auto_now=True, help_text='When this cache entry was last updated')),
            ],
            options={
                'verbose_name': 'GitHub API Cache',
                'verbose_name_plural': 'GitHub API Cache Entries',
                'ordering': ['-cached_at'],
            },
        ),
    ]
