# Generated by Django 5.2.5 on 2025-08-15 14:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_githubapicache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='User-friendly name for this alert', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('enabled', models.BooleanField(default=True)),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('disk', 'Disk Usage'), ('network_rx', 'Network Received'), ('network_tx', 'Network Transmitted'), ('custom', 'Custom Metric')], max_length=20)),
                ('custom_metric_name', models.CharField(blank=True, help_text='For custom metrics', max_length=100)),
                ('condition_operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal To'), ('ne', 'Not Equal To')], max_length=10)),
                ('threshold_value', models.FloatField(help_text='Threshold value to trigger alert')),
                ('time_window_minutes', models.PositiveIntegerField(default=5, help_text='Time window in minutes to evaluate the condition', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('evaluation_frequency_minutes', models.PositiveIntegerField(default=5, help_text='How often to check this condition', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('frequency_type', models.CharField(choices=[('immediate', 'Immediate'), ('throttled', 'Throttled'), ('scheduled', 'Scheduled'), ('batched', 'Batched')], default='throttled', max_length=20)),
                ('throttle_minutes', models.PositiveIntegerField(default=60, help_text='Minimum minutes between alerts of this type', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('schedule_cron', models.CharField(blank=True, help_text='Cron expression for scheduled alerts', max_length=100)),
                ('advanced_config', models.JSONField(blank=True, default=dict, help_text='Advanced configuration options')),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDeliveryMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_type', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Custom Webhook'), ('sms', 'SMS')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict, help_text='Delivery-specific configuration (e.g., email addresses, webhook URLs)')),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=5)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_methods', to='api.alertconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Delivery Method',
                'verbose_name_plural': 'Alert Delivery Methods',
                'ordering': ['delivery_type'],
            },
        ),
        migrations.CreateModel(
            name='AlertExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('throttled', 'Throttled')], max_length=20)),
                ('metric_value', models.FloatField(help_text='The metric value that triggered this alert')),
                ('threshold_value', models.FloatField(help_text='The threshold that was exceeded')),
                ('delivery_results', models.JSONField(default=dict, help_text='Results of delivery attempts for each configured method')),
                ('error_message', models.TextField(blank=True)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.alertconfiguration')),
            ],
            options={
                'verbose_name': 'Alert Execution',
                'verbose_name_plural': 'Alert Executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('system', 'System'), ('alert', 'Alert')], default='info', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, help_text="e.g., 'alerts', 'system', 'integrations'", max_length=50)),
                ('source', models.CharField(blank=True, help_text='Source system or component', max_length=100)),
                ('delivery_methods', models.JSONField(default=list, help_text='List of delivery methods used for this notification')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('alert_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.alertconfiguration')),
                ('alert_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.alertexecution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification History',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('min_severity_email', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', help_text='Minimum severity for email alerts', max_length=10)),
                ('min_severity_push', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', help_text='Minimum severity for push notifications', max_length=10)),
                ('max_emails_per_hour', models.PositiveIntegerField(default=10, help_text='Maximum emails to send per hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_push_per_hour', models.PositiveIntegerField(default=50, help_text='Maximum push notifications per hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('group_similar_alerts', models.BooleanField(default=True, help_text='Group similar alerts together')),
                ('auto_mark_read_after_minutes', models.PositiveIntegerField(default=0, help_text='Auto-mark notifications as read after X minutes (0 = disabled)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Preferences',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['user', 'enabled'], name='api_alertco_user_id_bcfc79_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['metric_type', 'enabled'], name='api_alertco_metric__5c5069_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['last_evaluated'], name='api_alertco_last_ev_cda23f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertdeliverymethod',
            unique_together={('alert_configuration', 'delivery_type')},
        ),
        migrations.AddIndex(
            model_name='alertexecution',
            index=models.Index(fields=['alert_configuration', 'executed_at'], name='api_alertex_alert_c_f2e5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertexecution',
            index=models.Index(fields=['status'], name='api_alertex_status_4921f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', 'read'], name='api_notific_user_id_2c1f27_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', 'delivered_at'], name='api_notific_user_id_a2d438_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['category'], name='api_notific_categor_758b41_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['notification_type'], name='api_notific_notific_902778_idx'),
        ),
    ]
